import type { Metadata } from 'next';
import './globals.css';
// import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// const pretendard = localFont({
//   src: '../../public/fonts/PretendardVariable.ttf',
//   style: 'normal',
//   variable: '--font-pretendard',
// });

// const pretendard = localFont({
//   src: [
//     {
//       path: '../../public/fonts/Pretendard-Black.ttf',
//       weight: '700',
//       style: 'normal',
//     },
//     {
//       path: '../../public/fonts/Pretendard-Regular.ttf',
//       weight: '400',
//       style: 'normal',
//     },
//   ],
//   display: 'swap',
//   variable: '--font-pretendard',
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link
          rel="stylesheet"
          as="style"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head> */}
      {/* <body className={`${pretendard.variable} antialiased`}>{children}</body> */}
      <body>{children}</body>
    </html>
  );
}
